name: pydexp
dependencies:
- python>=3.5
- anaconda
- pip
#- pygimli
- pip:
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - sphinx
  - sphinx-gallery
  - sphinx_bootstrap_theme
  - numpydoc
  - pandas
  - mpl_axes_aligner

