"""
Test example for gallery autogenerated by Sphinx
--------------------------------------------------------------------

Plot 2d randomn data 

"""
import matplotlib.pyplot as plt
import numpy as np
import dEXP as dEXP
from dEXP import _fit
import plot_dEXP as pEXP
import set_parameters as para
import examples.sources_mag.fwd_mag_sphere as magfwd

# Create a model using geometric objects from fatiando.mesher
plt.figure()
plt.imshow(np.random.random((50,50)))
plt.colorbar()
plt.show()
